module.exports = {
  START: 'START',
  STOP: 'STOP',
  PROCESS: 'PROCESS',
  DECISION: 'DECISION',
  SEND_EMAIL: 'SEND_EMAIL',
  CSV_READER: 'CSV_READER',
  GET_HTML: 'GET_HTML',
  PROMPT: 'PROMPT',
  EXEC: 'EXEC'
}
